import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "M Aqib Malik",
    description: "Generated by create M Aqib Malik",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={'custom-scrollbar overflow-y-scroll'}>
        <body className={`${inter.className} bg-slate-900 leading-relaxed text-slate-400 antialiased selection:bg-teal-300 selection:text-teal-900"`}>
        <Navbar />
        {children}
        <Footer />
        </body>
        </html>
    );
}
